<?php

namespace Database\Seeders;

use App\Enums\TipoLancamento;
use App\Models\Categoria;
use App\Models\Cliente;
use App\Models\Fornecedor;
use App\Models\Lancamento;
use App\Models\Lote;
use App\Models\Marca;
use App\Models\Motorista;
use App\Models\Produto;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class FillBasicData extends Seeder
{
    /**
     * Run the database seeds
     *
     * @return void
     */
    public function run()
    {
        $data =
            [
                'name' => 'Administrador',
                'email' => 'administrador@email.com',
                'email_verified_at' => now(),
                'password' => Hash::make('mudar@123'), // password

            ];
        User::create($data);
        $produtos = [];
        $produtos[]= ['nome'=> 'Pão Francês','unidade' => 'Und','precos' => ['a' =>0.40,'b' => 0.50,'c'=>0.55,'d' => 0.60,'e'=> 0.70,'f' => 0.53,'g' => 0, 'h' => 0]];
        $produtos[]= ['nome'=> 'Pão Francês embalado individual','unidade' => 'Und','precos' => ['a' =>0.55,'b' => 0.65,'c'=>0.70,'d' => 0.75,'e'=> 0.85,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Pão Francês Integral','unidade' => 'Und','precos' => ['a' =>0.75,'b' => 0.75,'c'=>0.75,'d' => 0.75,'e'=> 0.75,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Pão Francês Integral embalado individual','unidade' => 'Und','precos' => ['a' =>0.90,'b' => 0.90,'c'=>0.90,'d' => 0.90,'e'=> 0.90,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Pão de Leite','unidade' => 'Und','precos' => ['a' =>0.55,'b' => 0.50,'c'=>0.55,'d' => 0.60,'e'=> 0.70,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Pão de Leite embalado individual','unidade' => 'Und','precos' => ['a' =>0.70,'b' => 0.65,'c'=>0.70,'d' => 0.75,'e'=> 0.85,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Pão de Leite Integral','unidade' => 'Und','precos' => ['a' =>0.75,'b' => 0.75,'c'=>0.75,'d' => 0.75,'e'=> 0.75,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Pão de Leite Integral embalado individual ','unidade' => 'Und','precos' => ['a' =>0.90,'b' => 0.90,'c'=>0.90,'d' => 0.90,'e'=> 0.90,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Pão de Milho','unidade' => 'Und','precos' => ['a' =>0.65,'b' => 0.65,'c'=>0.65,'d' => 0.65,'e'=> 0.75,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Pão de Miho embalado individual','unidade' => 'Und','precos' => ['a' =>0.80,'b' => 0.80,'c'=>0.80,'d' => 0.80,'e'=> 0.90,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Pão de Coco','unidade' => 'Und','precos' => ['a' =>0.65,'b' => 0.65,'c'=>0.65,'d' => 0.65,'e'=> 0.75,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Pão de Coco embalado individual','unidade' => 'Und','precos' => ['a' =>0.80,'b' => 0.80,'c'=>0.80,'d' => 0.80,'e'=> 0.90,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Pão de Creme','unidade' => 'Und','precos' => ['a' =>0.80,'b' => 0.80,'c'=>0.80,'d' => 0.80,'e'=> 0.80,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Pão de Creme embalado individual','unidade' => 'Und','precos' => ['a' =>0.95,'b' => 0.95,'c'=>0.95,'d' => 0.95,'e'=> 0.95,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Pão de Batata','unidade' => 'Und','precos' => ['a' =>0.75,'b' => 0.75,'c'=>0.75,'d' => 0.75,'e'=> 0.75,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Pão de Mandioquinha','unidade' => 'Und','precos' => ['a' =>0.85,'b' => 0.85,'c'=>0.85,'d' => 0.85,'e'=> 0.85,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Pão de Mandioquinha embalado individual','unidade' => 'Und','precos' => ['a' =>1.0,'b' => 1.0,'c'=>1.0,'d' => 1.0,'e'=> 1.0,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Pão francês com margarina ','unidade' => 'Und','precos' => ['a' =>1.0,'b' => 1.0,'c'=>1.0,'d' => 1.15,'e'=> 1.25,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Pão de Leite com margarina ','unidade' => 'Und','precos' => ['a' =>1.0,'b' => 1.0,'c'=>1.0,'d' => 1.15,'e'=> 1.25,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Pão de Milho com margarina','unidade' => 'Und','precos' => ['a' =>1.0,'b' => 1.0,'c'=>1.0,'d' => 1.15,'e'=> 1.25,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Pão de Creme com margarina','unidade' => 'Und','precos' => ['a' =>1.25,'b' => 1.25,'c'=>1.25,'d' => 1.35,'e'=> 1.50,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Pão de Cenoura com margarina','unidade' => 'Und','precos' => ['a' =>1.0,'b' => 1.0,'c'=>1.0,'d' => 1.15,'e'=> 1.25,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Pão com frios','unidade' => 'Und','precos' => ['a' =>3.25,'b' => 3.25,'c'=>3.75,'d' => 3.75,'e'=> 3.75,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Pão com mortadela','unidade' => 'Und','precos' => ['a' =>3.0,'b' => 3.0,'c'=>3.0,'d' => 3.0,'e'=> 3.0,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Mini Pão Francês','unidade' => 'Und','precos' => ['a' =>0.40,'b' => 0.40,'c'=>0.40,'d' => 0.40,'e'=> 0.40,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Mini Pão Francês embalado individual','unidade' => 'Und','precos' => ['a' =>0.55,'b' => 0.55,'c'=>0.55,'d' => 0.55,'e'=> 0.55,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Mini Pão de Leite','unidade' => 'Und','precos' => ['a' =>0.40,'b' => 0.40,'c'=>0.40,'d' => 0.40,'e'=> 0.40,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Mini Pão de Leite embalado individual','unidade' => 'Und','precos' => ['a' =>0.55,'b' => 0.55,'c'=>0.55,'d' => 0.55,'e'=> 0.55,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Mini Pão de Batata','unidade' => 'Und','precos' => ['a' =>0.55,'b' => 0.55,'c'=>0.55,'d' => 0.55,'e'=> 0.55,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Mini Pão de Batata embalado individual','unidade' => 'Und','precos' => ['a' =>0.70,'b' => 0.70,'c'=>0.70,'d' => 0.70,'e'=> 0.70,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Mini Pão de Mandioquinha','unidade' => 'Und','precos' => ['a' =>0.55,'b' => 0.55,'c'=>0.55,'d' => 0.55,'e'=> 0.55,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Mini Pão de Mandioquinha embalado individual','unidade' => 'Und','precos' => ['a' =>0.70,'b' => 0.70,'c'=>0.70,'d' => 0.70,'e'=> 0.70,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Mini Pão de Cenoura','unidade' => 'Und','precos' => ['a' =>0.55,'b' => 0.55,'c'=>0.55,'d' => 0.55,'e'=> 0.55,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Mini Pão de Cenoura embalado individual','unidade' => 'Und','precos' => ['a' =>0.70,'b' => 0.70,'c'=>0.70,'d' => 0.70,'e'=> 0.70,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Mini Pão de Brioche','unidade' => 'Und','precos' => ['a' =>0.75,'b' => 0.75,'c'=>0.75,'d' => 0.75,'e'=> 0.75,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Mini Pão de Brioche embalado individual','unidade' => 'Und','precos' => ['a' =>0.90,'b' => 0.90,'c'=>0.90,'d' => 0.90,'e'=> 0.90,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Mini Pão Australiano','unidade' => 'Und','precos' => ['a' =>0.75,'b' => 0.75,'c'=>0.75,'d' => 0.75,'e'=> 0.75,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Mini Pão Australiano embalado individual','unidade' => 'Und','precos' => ['a' =>0.90,'b' => 0.90,'c'=>0.90,'d' => 0.90,'e'=> 0.90,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Bisnaguinha pct 300g','unidade' => 'Pct','precos' => ['a' =>4.50,'b' => 4.50,'c'=>4.50,'d' => 4.50,'e'=> 4.50,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Bisnaguinha Integral pct 300g','unidade' => 'Pct','precos' => ['a' =>5.0,'b' => 5.0,'c'=>5.0,'d' => 5.0,'e'=> 5.0,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Hotdog 50g','unidade' => 'Und','precos' => ['a' =>0.55,'b' => 0.55,'c'=>0.55,'d' => 0.55,'e'=> 0.55,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Hotdog Integral 50g','unidade' => 'Und','precos' => ['a' =>0.65,'b' => 0.65,'c'=>0.65,'d' => 0.65,'e'=> 0.65,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Hotdog 80g','unidade' => 'Und','precos' => ['a' =>0.80,'b' => 0.80,'c'=>0.80,'d' => 0.80,'e'=> 0.80,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Hambúrguer tradicional aro 10 - 50g','unidade' => 'Und','precos' => ['a' =>0.85,'b' => 0.85,'c'=>0.85,'d' => 0.85,'e'=> 0.85,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Hambúrguer tradicional aro 13 - 80g','unidade' => 'Und','precos' => ['a' =>1.30,'b' => 1.30,'c'=>1.30,'d' => 1.30,'e'=> 1.30,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Hambúrguer brioche aro 10 - 50g','unidade' => 'Und','precos' => ['a' =>1.25,'b' => 1.25,'c'=>1.25,'d' => 1.25,'e'=> 1.25,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Hambúrguer brioche aro 13 - 80g','unidade' => 'Und','precos' => ['a' =>2.0,'b' => 2.0,'c'=>2.0,'d' => 2.0,'e'=> 2.0,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Hambúrguer australiano aro 10 - 50g','unidade' => 'Und','precos' => ['a' =>1.25,'b' => 1.25,'c'=>1.25,'d' => 1.25,'e'=> 1.25,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Hambúrguer australiano aro 13 80g','unidade' => 'Und','precos' => ['a' =>2.0,'b' => 2.0,'c'=>2.0,'d' => 2.0,'e'=> 2.0,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Sovado 500g','unidade' => 'Und','precos' => ['a' =>5.3,'b' => 5.3,'c'=>5.3,'d' => 5.3,'e'=> 5.3,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Mini Sovado 60g','unidade' => 'Und','precos' => ['a' =>1.0,'b' => 1.0,'c'=>1.0,'d' => 1.0,'e'=> 1.0,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Mini Rosca Açúcarada 50g','unidade' => 'Und','precos' => ['a' =>1.20,'b' => 1.20,'c'=>1.20,'d' => 1.20,'e'=> 1.20,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Broa de Fubá pct 5 unidades','unidade' => 'Pct','precos' => ['a' =>10,'b' => 10,'c'=>10,'d' => 10,'e'=> 10,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Broa de Coco pct 5 unidades','unidade' => 'Pct','precos' => ['a' =>12.0,'b' => 12.0,'c'=>12.0,'d' => 12.0,'e'=> 12.0,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Broa de Fubá com gotas pct 5 unidades','unidade' => 'Pct','precos' => ['a' =>12.0,'b' => 12.0,'c'=>12.0,'d' => 12.0,'e'=> 12.0,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Farinha de Rosca','unidade' => 'KG','precos' => ['a' =>7.50,'b' => 7.50,'c'=>7.50,'d' => 7.50,'e'=> 7.50,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Mini Croissant','unidade' => 'Und','precos' => ['a' =>1.0,'b' => 1.0,'c'=>1.0,'d' => 1.0,'e'=> 1.0,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Mini Carolina Doce de Leite','unidade' => 'Und','precos' => ['a' =>1.0,'b' => 1.0,'c'=>1.0,'d' => 1.0,'e'=> 1.0,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Mini Sonho ','unidade' => 'Und','precos' => ['a' =>1.70,'b' => 1.70,'c'=>1.70,'d' => 1.70,'e'=> 1.70,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Mini Salgado Assado','unidade' => 'Und','precos' => ['a' =>0.90,'b' => 0.90,'c'=>0.90,'d' => 0.90,'e'=> 0.90,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Mini Salgado Frito','unidade' => 'Und','precos' => ['a' =>0.90,'b' => 0.90,'c'=>0.90,'d' => 0.90,'e'=> 0.90,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Lanche de Metro Presunto e Queijo','unidade' => 'Und','precos' => ['a' =>65,'b' => 65,'c'=>65,'d' => 65,'e'=> 65,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Lanche de Metro Peito de Peru e Queijo Minas','unidade' => 'Und','precos' => ['a' =>75,'b' => 75,'c'=>75,'d' => 75,'e'=> 75,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Lanche de Metro Salame e Queijo Cheddar','unidade' => 'Und','precos' => ['a' =>85,'b' => 85,'c'=>85,'d' => 85,'e'=> 85,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Mini Lanche no Pão de Brioche','unidade' => 'Und','precos' => ['a' =>1.80,'b' => 1.80,'c'=>1.80,'d' => 1.80,'e'=> 1.80,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Mini Lanche no Pão de Leite','unidade' => 'Und','precos' => ['a' =>1.80,'b' => 1.80,'c'=>1.80,'d' => 1.80,'e'=> 1.80,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Bolo Confeitado forma 4 (30 fatias)','unidade' => 'Und','precos' => ['a' =>185,'b' => 185,'c'=>185,'d' => 185,'e'=> 185,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Bolo Confeitado forma 5 (40 fatias)','unidade' => 'Und','precos' => ['a' =>250,'b' => 250,'c'=>250,'d' => 250,'e'=> 250,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Bolo Confeitado forma 6 (60 fatias)','unidade' => 'Und','precos' => ['a' =>285,'b' => 285,'c'=>285,'d' => 285,'e'=> 285,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Bolo Confeitado forma 7 (80 fatias)','unidade' => 'Und','precos' => ['a' =>340,'b' => 340,'c'=>340,'d' => 340,'e'=> 340,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Bolo 500g - Coco','unidade' => 'Und','precos' => ['a' =>12,'b' => 12,'c'=>12,'d' => 12,'e'=> 12,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Bolo 500g - Laranja','unidade' => 'Und','precos' => ['a' =>12,'b' => 12,'c'=>12,'d' => 12,'e'=> 12,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Bolo 500g - Baunilha','unidade' => 'Und','precos' => ['a' =>12,'b' => 12,'c'=>12,'d' => 12,'e'=> 12,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Bolo 500g - Limão','unidade' => 'Und','precos' => ['a' =>12,'b' => 12,'c'=>12,'d' => 12,'e'=> 12,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Bolo 500g - Abacaxi','unidade' => 'Und','precos' => ['a' =>12,'b' => 12,'c'=>12,'d' => 12,'e'=> 12,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Bolo 500g - Chocolate','unidade' => 'Und','precos' => ['a' =>12,'b' => 12,'c'=>12,'d' => 12,'e'=> 12,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Bolo 500g - Formigueiro','unidade' => 'Und','precos' => ['a' =>12,'b' => 12,'c'=>12,'d' => 12,'e'=> 12,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Bolo 500g - Mesclado','unidade' => 'Und','precos' => ['a' =>12,'b' => 12,'c'=>12,'d' => 12,'e'=> 12,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Bolo 500g - Cenoura','unidade' => 'Und','precos' => ['a' =>12,'b' => 12,'c'=>12,'d' => 12,'e'=> 12,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Bolo 500g - Cenoura com cobertura','unidade' => 'Und','precos' => ['a' =>17,'b' => 17,'c'=>17,'d' => 17,'e'=> 17,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Bolo 1,500Kg - Coco','unidade' => 'Und','precos' => ['a' =>30,'b' => 30,'c'=>30,'d' => 30,'e'=> 30,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Bolo 1,500Kg - Laranja','unidade' => 'Und','precos' => ['a' =>30,'b' => 30,'c'=>30,'d' => 30,'e'=> 30,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Bolo 1,500Kg - Baunilha','unidade' => 'Und','precos' => ['a' =>30,'b' => 30,'c'=>30,'d' => 30,'e'=> 30,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Bolo 1,500Kg - Limão','unidade' => 'Und','precos' => ['a' =>30,'b' => 30,'c'=>30,'d' => 30,'e'=> 30,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Bolo 1,500Kg - Abacaxi','unidade' => 'Und','precos' => ['a' =>30,'b' => 30,'c'=>30,'d' => 30,'e'=> 30,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Bolo 1,500Kg - Chocolate','unidade' => 'Und','precos' => ['a' =>30,'b' => 30,'c'=>30,'d' => 30,'e'=> 30,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Bolo 1,500Kg - Formigueiro','unidade' => 'Und','precos' => ['a' =>30,'b' => 30,'c'=>30,'d' => 30,'e'=> 30,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Bolo 1,500Kg - Mesclado','unidade' => 'Und','precos' => ['a' =>30,'b' => 30,'c'=>30,'d' => 30,'e'=> 30,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Bolo 1,500Kg - Cenoura','unidade' => 'Und','precos' => ['a' =>30,'b' => 30,'c'=>30,'d' => 30,'e'=> 30,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Bolo 1,500Kg - Cenoura com cobertura','unidade' => 'Und','precos' => ['a' =>36,'b' => 36,'c'=>36,'d' => 36,'e'=> 36,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Bolo em Placa 4Kg - Coco','unidade' => 'Und','precos' => ['a' =>80,'b' => 80,'c'=>80,'d' => 80,'e'=> 80,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Bolo em Placa 4Kg - Laranja','unidade' => 'Und','precos' => ['a' =>80,'b' => 80,'c'=>80,'d' => 80,'e'=> 80,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Bolo em Placa 4Kg - Baunilha','unidade' => 'Und','precos' => ['a' =>80,'b' => 80,'c'=>80,'d' => 80,'e'=> 80,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Bolo em Placa 4Kg - Limão','unidade' => 'Und','precos' => ['a' =>80,'b' => 80,'c'=>80,'d' => 80,'e'=> 80,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Bolo em Placa 4Kg - Abacaxi','unidade' => 'Und','precos' => ['a' =>80,'b' => 80,'c'=>80,'d' => 80,'e'=> 80,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Bolo em Placa 4Kg - Chocolate','unidade' => 'Und','precos' => ['a' =>80,'b' => 80,'c'=>80,'d' => 80,'e'=> 80,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Bolo em Placa 4Kg - Formigueiro','unidade' => 'Und','precos' => ['a' =>80,'b' => 80,'c'=>80,'d' => 80,'e'=> 80,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Bolo em Placa 4Kg - Mesclado','unidade' => 'Und','precos' => ['a' =>80,'b' => 80,'c'=>80,'d' => 80,'e'=> 80,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Bolo em Placa 4Kg - Cenoura','unidade' => 'Und','precos' => ['a' =>80,'b' => 80,'c'=>80,'d' => 80,'e'=> 80,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Pão Francês Congelado - Vermelho','unidade' => 'Pct','precos' => ['a' =>38.50,'b' => 38.50,'c'=>38.50,'d' => 44.80,'e'=> 44.80,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Pão Francês Congelado - Azul','unidade' => 'Pct','precos' => ['a' =>38.50,'b' => 38.50,'c'=>38.50,'d' => 44.80,'e'=> 44.80,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Pão de Leite Congelado - Amarelo','unidade' => 'Pct','precos' => ['a' =>44.80,'b' => 44.80,'c'=>44.80,'d' => 48.30,'e'=> 48.30,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Pão Francês Integral Congelado - Marrom','unidade' => 'Pct','precos' => ['a' =>44.80,'b' => 44.80,'c'=>44.80,'d' => 48.30,'e'=> 48.30,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Pão de Queijo Congelado 1Kg','unidade' => 'Pct','precos' => ['a' =>29.0,'b' => 29.0,'c'=>29.0,'d' => 29.0,'e'=> 29.0,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Pão de Queijo Assado 1Kg','unidade' => 'Pct','precos' => ['a' =>29.0,'b' => 29.0,'c'=>29.0,'d' => 29.0,'e'=> 29.0,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Mini Pão Fancês Integral','unidade' => 'Und','precos' => ['a' =>0.55,'b' => 0.55,'c'=>0.55,'d' => 0.55,'e'=> 0.55,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Mini Pão Fancês Integral Embalado Individual','unidade' => 'Und','precos' => ['a' =>0.70,'b' => 0.70,'c'=>0.70,'d' => 0.70,'e'=> 0.70,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Mini Pão de Milho','unidade' => 'Und','precos' => ['a' =>0.50,'b' => 0.50,'c'=>0.50,'d' => 0.50,'e'=> 0.50,'f'=> 0,'g'=> 0,'h' => 0]];
        $produtos[]= ['nome'=> 'Mini Pão de Milho Embalado Individual','unidade' => 'Und','precos' => ['a' =>0.65,'b' => 0.65,'c'=>0.65,'d' => 0.65,'e'=> 0.65,'f'=> 0,'g'=> 0,'h' => 0]];
        foreach ($produtos as $produto) {
            Produto::create($produto);
        }

        $motoristas = [];
        $motoristas[] = ['nome' => 'RETIRADO Manhã','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'NILDO 1ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'NILDO 2ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'NILDO 3ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'ANDRÉ 1ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'ANDRÉ 2ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'ANDRÉ 3ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'ALEX 1ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'ALEX 2ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'ALEX 3ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'ALEX 4ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'VALDIR 1ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'VALDIR 2ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'VALDIR 3ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'NEI 1ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'NEI 2ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'NEI 3ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'JEFINHO 1ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'JEFINHO 2ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'JEFINHO 3ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'BOCA Viagem única','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'RETIRADO Tarde','turno' => 'TARDE'];
        $motoristas[] = ['nome' => 'NEI TARDE ','turno' => 'TARDE'];
        $motoristas[] = ['nome' => 'JOÃO 1ª Viagem','turno' => 'TARDE'];
        $motoristas[] = ['nome' => 'JOÃO 2ª Viagem','turno' => 'TARDE'];
        $motoristas[] = ['nome' => 'JOÃO 3ª Viagem','turno' => 'TARDE'];
        $motoristas[] = ['nome' => 'JOÃO 4ª Viagem','turno' => 'TARDE'];
        $motoristas[] = ['nome' => 'RETIRADO Sábado','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'Valdir / André Sábado 1ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'Valdir / André Sábado 2ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'Valdir / André Sábado 3ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'ALEX Sábado 1ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'ALEX Sábado 2ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'ALEX Sábado 3ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'ALEX Sábado 4ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'Nei / Nildo Sábado 1ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'Nei / Nildo Sábado 2ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'Nei / Nildo Sábado 3ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'Jefinho / César Sábado 1ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'Jefinho / César Sábado 2ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'Jefinho / César Sábado 3ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'JOÃO Sábado 1ª Viagem','turno' => 'TARDE'];
        $motoristas[] = ['nome' => 'JOÃO Sábado 2ª Viagem','turno' => 'TARDE'];
        $motoristas[] = ['nome' => 'JOÃO Sábado 3ª Viagem','turno' => 'TARDE'];
        $motoristas[] = ['nome' => 'JOÃO Sábado 4ª Viagem','turno' => 'TARDE'];
        $motoristas[] = ['nome' => 'RETIRADO Domingo','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'Valdir / André Domingo 1ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'Valdir / André Domingo 2ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'Valdir / André Domingo 3ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'César / Nildo Domingo 1ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'César / Nildo Domingo 2ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'César / Nildo Domingo 3ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'César / Nildo Domingo 4ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'Jefinho / Nei Domingo 1ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'Jefinho / Nei Domingo 2ª Viagem','turno' => 'MANHÃ'];
        $motoristas[] = ['nome' => 'Jefinho / Nei Domingo 3ª Viagem','turno' => 'MANHÃ'];
        foreach ($motoristas as $motorista) {
            Motorista::create($motorista);
        }
        $clientes = [];
       
$clientes[]= ['name'=>'Majijo ','cnpj' => '14202745/0001-48','logradouro' => 'Av. Dep. Benedito Matarazzo','numero' => '10631','bairro' => 'Jardim Sao Jose','cidade' => 'São José dos Campos','complemento' => '','cep' => '12216-340','tipo_cliente' => 'b'];
$clientes[]= ['name'=>'Hospital Municipal','cnpj' => '61699567/0012-45','logradouro' => 'R. Saigiro Nakamura','numero' => '800','bairro' => 'Vila Industrial','cidade' => 'São José dos Campos','complemento' => '','cep' => '12220-280','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Volks (Sapore)','cnpj' => '67945071/0001-38','logradouro' => 'Av. Carlos Pedroso da Silveira','numero' => '10000','bairro' => 'Jardim Santa Tereza','cidade' => 'Taubaté','complemento' => '','cep' => '12043-000','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Rochinha (Majijo)','cnpj' => '14583109/0001-03','logradouro' => 'Av. Dois','numero' => '120','bairro' => 'Eldorado','cidade' => 'São José dos Campos','complemento' => '','cep' => '12238-580','tipo_cliente' => 'b'];
$clientes[]= ['name'=>'Ferrusmol','cnpj' => '59407148/0001-98','logradouro' => 'R. Colombo','numero' => '120','bairro' => 'Jardim Oriente','cidade' => 'São José dos Campos','complemento' => '','cep' => '12236-120','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'Tecplas Jd América','cnpj' => '56840077/0001-24','logradouro' => 'R. Serra do Roncador','numero' => '377','bairro' => 'Jardim Anhembi','cidade' => 'São José dos Campos','complemento' => '','cep' => '12235-240','tipo_cliente' => 'd'];
$clientes[]= ['name'=>'Lar do Idoso Miguel Arcanjo','cnpj' => '24959682/0001-22','logradouro' => 'Praça Mikado','numero' => '21','bairro' => 'Jardim Oriente','cidade' => 'São José dos Campos','complemento' => '','cep' => '12236-160','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'Alvotec  ','cnpj' => '36716037/0001-68','logradouro' => 'R. Romualdo Davoli','numero' => '50','bairro' => 'Eldorado','cidade' => 'São José dos Campos','complemento' => '','cep' => '12238-577','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'Benacchio','cnpj' => '07599523/0001-45','logradouro' => 'R. Salviano José da Silva','numero' => '205','bairro' => 'Eldorado','cidade' => 'São José dos Campos','complemento' => '','cep' => '12238-573','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'Swissbras ','cnpj' => '06222419/0001-74','logradouro' => 'R. José Sierra','numero' => '211','bairro' => 'Eldorado','cidade' => 'São José dos Campos','complemento' => '','cep' => '12238-571','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'Brascam ','cnpj' => '10426147/0001-00','logradouro' => 'R. José Sierra','numero' => '81','bairro' => 'Eldorado','cidade' => 'São José dos Campos','complemento' => '','cep' => '12238-571','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'MCG-Farmaceutica','cnpj' => '18755529/0001-80','logradouro' => 'AV ENGENHEIRO JUAREZ DE SIQUEIRA BRITTO WANDERLEY','numero' => '240','bairro' => 'Eldorado','cidade' => 'São José dos Campos','complemento' => '','cep' => '12238-565','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'MCG Perfumaria','cnpj' => '30874801/0001-47','logradouro' => 'R SALVIANO JOSE DA SILVA','numero' => '145','bairro' => 'Eldorado','cidade' => 'São José dos Campos','complemento' => '','cep' => '12238-573','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'MCG Suplementos','cnpj' => '14600578/0001-93','logradouro' => 'R. Caravelas','numero' => '65','bairro' => 'Jardim Vale do Sol','cidade' => 'São José dos Campos','complemento' => '','cep' => '12238-170','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'São Pedro','cnpj' => '','logradouro' => 'Rua Paulino massahiro tamashiro','numero' => '19','bairro' => 'Santa Paula','cidade' => 'Jacareí','complemento' => '','cep' => '12302-246','tipo_cliente' => 'a'];
$clientes[]= ['name'=>'Elian ','cnpj' => '','logradouro' => 'Av Rio de Janeiro','numero' => '485','bairro' => 'Rio Comprido','cidade' => 'Jacareí','complemento' => '','cep' => '12302-130','tipo_cliente' => 'a'];
$clientes[]= ['name'=>'Josias ','cnpj' => '','logradouro' => 'Av Rio de Janeiro','numero' => '569','bairro' => 'Rio Comprido','cidade' => 'Jacareí','complemento' => '','cep' => '12302-130','tipo_cliente' => 'a'];
$clientes[]= ['name'=>'Mercadinho Familia ','cnpj' => '','logradouro' => 'Av Rio de Janeiro','numero' => '636','bairro' => 'Rio Comprido','cidade' => 'Jacareí','complemento' => '','cep' => '12302-130','tipo_cliente' => 'a'];
$clientes[]= ['name'=>'SK Automative','cnpj' => '08237002/0001-34','logradouro' => 'R. Joaçaba','numero' => '271','bairro' => 'Chácaras Reunidas','cidade' => 'São José dos Campos','complemento' => '','cep' => '12238-530','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'Graúna','cnpj' => '03011370/0001-12','logradouro' => 'R. Januária','numero' => '1100','bairro' => 'Chácaras Reunidas','cidade' => 'São José dos Campos','complemento' => '','cep' => '12238-500','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'Brasilit  (Boas Vindas)','cnpj' => '66140955/0001-52','logradouro' => 'Av. do Cristal','numero' => '540','bairro' => 'Jardim California','cidade' => 'Jacareí','complemento' => '','cep' => '12311-210','tipo_cliente' => 'd'];
$clientes[]= ['name'=>'Ardagh (Sapore)','cnpj' => '67945071/0001-38','logradouro' => 'Rod. Geraldo Scavone','numero' => '2400','bairro' => 'Jardim California','cidade' => 'Jacareí','complemento' => '','cep' => '12305-490','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Safran (Dom Rubi)','cnpj' => '16580640/0001-58','logradouro' => 'Av. Getúlio Vargas','numero' => '3000','bairro' => 'Jardim Luiza','cidade' => 'Jacareí','complemento' => '','cep' => '12305-010','tipo_cliente' => 'b'];
$clientes[]= ['name'=>'JTU','cnpj' => '','logradouro' => 'Av. Getúlio Vargas','numero' => '3450','bairro' => 'Jardim Luiza','cidade' => 'Jacareí','complemento' => '','cep' => '12305-010','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Tarkett (Evita Refeições)','cnpj' => '01208118/0003-34','logradouro' => 'Av. Getúlio Vargas','numero' => '2185','bairro' => 'Jardim California','cidade' => 'Jacareí','complemento' => '','cep' => '12305-010','tipo_cliente' => 'c'];
$clientes[]= ['name'=>'Ideal Refeições','cnpj' => '01227687/0001-65','logradouro' => 'R. Abaeté','numero' => '180','bairro' => 'Jardim Ismenia','cidade' => 'São José dos Campos','complemento' => '','cep' => '12220-680','tipo_cliente' => 'c'];
$clientes[]= ['name'=>'PMSJC SEPAC - CSI','cnpj' => '46643466/0001-06','logradouro' => 'Estrada Dr. Altino Bondensan','numero' => '500','bairro' => 'Coqueiro','cidade' => 'São José dos Campos','complemento' => '','cep' => '12247-016','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'Prolind (Sr Mignon)','cnpj' => '36624431/0001-76','logradouro' => 'Rod. Pres. Dutra','numero' => 'KM138','bairro' => 'Eugênio de Melo','cidade' => 'São José dos Campos','complemento' => '','cep' => '12247-004','tipo_cliente' => 'c'];
$clientes[]= ['name'=>'Paraibuna','cnpj' => '46643474/0001-52','logradouro' => 'Avenida Benedito Nogueira Santos','numero' => '326','bairro' => 'Centro','cidade' => 'Paraibuna','complemento' => '','cep' => '12260-000','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Sesi Caçapava  ','cnpj' => '03779133/0127-06','logradouro' => 'Av. Monsenhor Theodomiro Lobo','numero' => '100','bairro' => 'Parque Res. Maria Elmira','cidade' => 'Caçapava','complemento' => '','cep' => '12285-000','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Sesi Taubate ','cnpj' => '03779133/0018-44','logradouro' => 'R. Expedicionário Teodoro Francisco Ribeiro','numero' => '325','bairro' => 'Vila Santa Isabel','cidade' => 'Taubaté','complemento' => '','cep' => '12050-540','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Prefeitura da Estância de Tremembé','cnpj' => '46638714/0001-20','logradouro' => 'R. 7 de Setembro','numero' => '701','bairro' => 'Tremembe','cidade' => 'Tremembé','complemento' => '','cep' => '12120-017','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Sesi Pinda','cnpj' => '03779133/0101-69','logradouro' => 'Av. Antenor da Silva Andrade','numero' => '183','bairro' => 'Campo Alegre','cidade' => 'Pindamonhagaba','complemento' => '','cep' => '12412-751','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Prefeitura de São Luiz do Paraitinga','cnpj' => '46631248/0001-51','logradouro' => 'Avenida Celestino Campos Coelho','numero' => '612','bairro' => 'São Benedito','cidade' => 'São Luiz do Paraitinga','complemento' => '','cep' => '12140-000','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Hospital Pio 12 (Rede Madre)','cnpj' => '60194990/0006-82','logradouro' => 'R. Paraguassú','numero' => '51','bairro' => 'Santana','cidade' => 'São José dos Campos','complemento' => '','cep' => '12212-110','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Recanto João de Deus (Rede Madre)','cnpj' => '60194990/0006-82','logradouro' => 'R. Paraguassú','numero' => '81','bairro' => 'Santana','cidade' => 'São José dos Campos','complemento' => '','cep' => '12212-110','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Radici (Splendida)','cnpj' => '44342914/0001-06','logradouro' => 'Rua Pedro Rachid','numero' => '846','bairro' => 'Santana','cidade' => 'São José dos Campos','complemento' => '','cep' => '12212-100','tipo_cliente' => 'd'];
$clientes[]= ['name'=>'PMSJC SSM Norte','cnpj' => '46643466/0001-06','logradouro' => 'R. Schaia Feigenson','numero' => '130','bairro' => 'Jardim Telespark','cidade' => 'São José dos Campos','complemento' => '','cep' => '12212-720','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC SSM Horto','cnpj' => '46643466/0001-06','logradouro' => 'R. Schaia Feigenson','numero' => '130','bairro' => 'Jardim Telespark','cidade' => 'São José dos Campos','complemento' => '','cep' => '12212-720','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'UPA Alto da Ponte (Dom Rubi)','cnpj' => '16580640/0001-58','logradouro' => 'Rua Alzíro Lebrão','numero' => '76','bairro' => 'Alto da Ponte','cidade' => 'São José dos Campos','complemento' => '','cep' => '12212-500','tipo_cliente' => 'b'];
$clientes[]= ['name'=>'Dom Rubi ','cnpj' => '16580640/0001-58','logradouro' => 'Rua: Carlos Marcondes ','numero' => '201','bairro' => 'Jardim Limoeiro','cidade' => 'São José dos Campos','complemento' => '','cep' => '12241-421','tipo_cliente' => 'b'];
$clientes[]= ['name'=>'SOLUTECH (Dom Rubi)','cnpj' => '16580640/0001-58','logradouro' => 'Rua: Carlos Marcondes ','numero' => '201','bairro' => 'Jardim Limoeiro','cidade' => 'São José dos Campos','complemento' => '','cep' => '12241-421','tipo_cliente' => 'b'];
$clientes[]= ['name'=>'EMBRAER (Dom Rubi)','cnpj' => '16580640/0001-58','logradouro' => 'Rua: Carlos Marcondes ','numero' => '201','bairro' => 'Jardim Limoeiro','cidade' => 'São José dos Campos','complemento' => '','cep' => '12241-421','tipo_cliente' => 'b'];
$clientes[]= ['name'=>'Viação Jacareí','cnpj' => '','logradouro' => 'Rod Presidente Dutra','numero' => 'KM 156','bairro' => 'Jardim Limoeiro','cidade' => 'São José dos Campos','complemento' => '','cep' => '12241-361','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Sr. Aparecido','cnpj' => '','logradouro' => 'R. Sergio Gonzaga Azevedo','numero' => '181','bairro' => 'Jardim Limoeiro','cidade' => 'São José dos Campos','complemento' => '','cep' => '12241-340','tipo_cliente' => 'a'];
$clientes[]= ['name'=>'Hospital Vivalle (Sodexo)','cnpj' => '49930514/0001-35','logradouro' => 'Av. Linneu de Moura','numero' => '995','bairro' => 'Urbanova','cidade' => 'São José dos Campos','complemento' => '','cep' => '12244-380','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Belacci (Qualita)','cnpj' => '44342914/0001-06','logradouro' => 'Estrada municipal Antenor de Sá ferreira','numero' => '1011','bairro' => 'Piedade','cidade' => 'Caçapava','complemento' => '','cep' => '12295-233','tipo_cliente' => 'd'];
$clientes[]= ['name'=>'Latecoere (Evita Refeições)','cnpj' => '01208118/0003-34','logradouro' => 'Av. Getúlio Dorneles Vargas','numero' => '3320','bairro' => 'Jardim Luiza','cidade' => 'Jacareí','complemento' => '','cep' => '12305-010','tipo_cliente' => 'c'];
$clientes[]= ['name'=>'Inylbra (Lallegro)','cnpj' => '60785995/0001-75','logradouro' => 'Av. Getúlio Dorneles Vargas','numero' => '2385','bairro' => 'Jardim Luiza','cidade' => 'Jacareí','complemento' => '','cep' => '12305-010','tipo_cliente' => 'd'];
$clientes[]= ['name'=>'Saae Logística','cnpj' => '48962625/0012-13','logradouro' => 'Av. Egídio Antônio Coimbra','numero' => '1228','bairro' => 'Parque dos Sinos','cidade' => 'Jacareí','complemento' => '','cep' => '12328-513','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Saae Dutra - ETE','cnpj' => '48962625/0012-13','logradouro' => 'Av. Malek assad','numero' => 'S/N','bairro' => 'Jardim Santa Maria','cidade' => 'Jacareí','complemento' => '','cep' => '12328-900','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Saae Centro - Sede','cnpj' => '48962625/0012-13','logradouro' => 'Rua Miguel Leite de Amparo ','numero' => '121','bairro' => 'Jardim Pereira do Amparo','cidade' => 'Jacareí','complemento' => '','cep' => '12301-730','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Saae Liberdade - ECA','cnpj' => '48962625/0012-13','logradouro' => 'Rua Aparicio Lorena ','numero' => '120','bairro' => 'Jardim Liberdade','cidade' => 'Jacareí','complemento' => '','cep' => '12300-460','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Saae Bela Vista - ETA','cnpj' => '48962625/0012-13','logradouro' => 'Rua Antunes da Costa ','numero' => '200','bairro' => 'Bela Vista','cidade' => 'Jacareí','complemento' => '','cep' => '12308-640','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Manutenção Saude Jacareí ','cnpj' => '46694139/0001-83','logradouro' => 'R:Nicolau Mercadante ','numero' => '146','bairro' => 'Centro','cidade' => 'Jacareí','complemento' => '','cep' => '12327-680','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'CAPS III AD Jacareí','cnpj' => '46694139/0001-83','logradouro' => 'AV. Major Acácio Ferreira','numero' => '620','bairro' => 'Centro','cidade' => 'Jacareí','complemento' => '','cep' => '12327-070','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'CAPS I  Infantil Jacareí','cnpj' => '46694139/0001-83','logradouro' => 'AV. Major Acácio Ferreira','numero' => '804','bairro' => 'Centro','cidade' => 'Jacareí','complemento' => '','cep' => '12327-070','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'CAPS II Jacareí','cnpj' => '46694139/0001-83','logradouro' => 'rua Dona Nenê Namura Abib','numero' => '134','bairro' => 'Residencial São Paulo','cidade' => 'Jacareí','complemento' => '','cep' => '12322-290','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'SESI Jacarei ','cnpj' => '03779133/0023-01','logradouro' => 'R. Antonio Ferreira Rizzin','numero' => '600','bairro' => 'Jardim Elza Maria','cidade' => 'Jacareí','complemento' => '','cep' => '12322-120','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Prefeitura de Igarata','cnpj' => '46694147/0001-20','logradouro' => 'Av. Benedito Rodrigues de Freitas','numero' => '330','bairro' => 'Centro','cidade' => 'Igaratá','complemento' => '','cep' => '12350-000','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'UPA Campo (Dom Rubi)','cnpj' => '16580640/0001-58','logradouro' => 'R. João Batista do Nascimento','numero' => '359','bairro' => 'Campo dos Alemães','cidade' => 'São José dos Campos','complemento' => '','cep' => '12239-170','tipo_cliente' => 'b'];
$clientes[]= ['name'=>'Vale Cargas Armazém','cnpj' => '04879999/0001-41','logradouro' => 'R. Guaianesia','numero' => '340','bairro' => 'Chácaras Reunidas','cidade' => 'São José dos Campos','complemento' => '','cep' => '12238-460','tipo_cliente' => 'd'];
$clientes[]= ['name'=>'Vale Cargas Logística','cnpj' => '04879999/0001-41','logradouro' => 'R. Guaianesia','numero' => '340','bairro' => 'Chácaras Reunidas','cidade' => 'São José dos Campos','complemento' => '','cep' => '12238-460','tipo_cliente' => 'd'];
$clientes[]= ['name'=>'Breda Bruno','cnpj' => '','logradouro' => 'Av George Eastman','numero' => '1481','bairro' => 'Conj. Res. Trinta e Um de Marco','cidade' => 'São José dos Campos','complemento' => '','cep' => '12237-640','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Maringá (portaria Breda)','cnpj' => '','logradouro' => 'Av George Eastman','numero' => '1481','bairro' => 'Conj. Res. Trinta e Um de Marco','cidade' => 'São José dos Campos','complemento' => '','cep' => '12237-640','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Nutrimenta ','cnpj' => '05671480/0001-36','logradouro' => 'R. Olinto de Aquino','numero' => '63','bairro' => 'Palmeiras de São José','cidade' => 'São José dos Campos','complemento' => '','cep' => '12237-360','tipo_cliente' => 'c'];
$clientes[]= ['name'=>'PMSJC Marronzinho','cnpj' => '46643466/0001-06','logradouro' => 'Av. Doutor Sebastiao Henrique da Cunha Pontes','numero' => '3300','bairro' => 'Jardim Anhembi','cidade' => 'São José dos Campos','complemento' => '','cep' => '12237-823','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'Saúde Mental (Ótima)','cnpj' => '48717946/0001-08','logradouro' => 'R. Pituba','numero' => '100','bairro' => 'Jardim Satélite','cidade' => 'São José dos Campos','complemento' => '','cep' => '12230-820','tipo_cliente' => 'c'];
$clientes[]= ['name'=>'Fragata','cnpj' => '41948086/0001-66','logradouro' => 'Av. Andrômeda','numero' => '3600','bairro' => 'Bosque dos Eucaliptos','cidade' => 'São José dos Campos','complemento' => '','cep' => '12233-000','tipo_cliente' => 'c'];
$clientes[]= ['name'=>'Urbam Torrão (Bonizzoni)','cnpj' => '11893767/0001-03','logradouro' => 'Estrada Municipal José Augusto Teixeira','numero' => '400','bairro' => 'Jardim Torrão de Ouro 2','cidade' => 'São José dos Campos','complemento' => '','cep' => '12229-840','tipo_cliente' => 'c'];
$clientes[]= ['name'=>'Serveng','cnpj' => '07444290/0001-01','logradouro' => 'Estr. de Varadouro','numero' => 'S/N','bairro' => 'Jardim Colonia','cidade' => 'Jambeiro','complemento' => '','cep' => '12315-020','tipo_cliente' => 'd'];
$clientes[]= ['name'=>'Avibras ','cnpj' => '13668070/0005-98','logradouro' => 'Estr. de Varadouro','numero' => '1200','bairro' => 'Jardim Colonia','cidade' => 'Jambeiro','complemento' => '','cep' => '12315-020','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'Fundação Casa','cnpj' => '20723388/0001-66','logradouro' => 'Rodovia dos Tamoios','numero' => 'KM 12','bairro' => 'Pernambucana','cidade' => 'São José dos Campos','complemento' => '','cep' => '12228-845','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'UPA Putim (Dom Rubi)','cnpj' => '16580640/0001-58','logradouro' => 'Av. João Rodolfo Castelli','numero' => '1035','bairro' => 'Putim','cidade' => 'São José dos Campos','complemento' => '','cep' => '12225-030','tipo_cliente' => 'b'];
$clientes[]= ['name'=>'PMSJC SSM Sudeste','cnpj' => '46643466/0001-06','logradouro' => 'R. Terezinha Cesar de Souza','numero' => '210','bairro' => 'Jardim Santa Júlia','cidade' => 'São José dos Campos','complemento' => '','cep' => '12228-324','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'CJ Engenharia - Obra U','cnpj' => '28425409/0001-79','logradouro' => 'Avenida Cidade Jardim','numero' => '831','bairro' => 'Jardim Satélite','cidade' => 'São José dos Campos','complemento' => '','cep' => '12231-675','tipo_cliente' => 'c'];
$clientes[]= ['name'=>'CJ Engenharia -Avante','cnpj' => '28425409/0001-79','logradouro' => 'Avenida Cidade Jardim','numero' => '831','bairro' => 'Jardim Satélite','cidade' => 'São José dos Campos','complemento' => '','cep' => '12231-675','tipo_cliente' => 'c'];
$clientes[]= ['name'=>'CJ Engenharia - São Judas','cnpj' => '28425409/0001-79','logradouro' => 'Avenida Cidade Jardim','numero' => '831','bairro' => 'Jardim Satélite','cidade' => 'São José dos Campos','complemento' => '','cep' => '12231-675','tipo_cliente' => 'c'];
$clientes[]= ['name'=>'PMSJC SSM Satélite','cnpj' => '46643466/0001-06','logradouro' => 'Av: Salinas','numero' => '170','bairro' => 'Jardim Satélite','cidade' => 'São José dos Campos','complemento' => '','cep' => '12233-593','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC SSM Arborização','cnpj' => '46643466/0001-06','logradouro' => 'Av: Salinas ','numero' => '170','bairro' => 'Jardim Satélite','cidade' => 'São José dos Campos','complemento' => '','cep' => '12233-593','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'Casa 01  (Abrapi)','cnpj' => '35252296/0001-12','logradouro' => 'Rua Caetité','numero' => '120','bairro' => 'Jardim Vale do Sol','cidade' => 'São José dos Campos','complemento' => '','cep' => '12238-130','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'Tecplas Eldorado','cnpj' => '56840077/0002-05','logradouro' => 'R. Serra do Roncador','numero' => '377','bairro' => 'Jardim Anhembi','cidade' => 'São José dos Campos','complemento' => '','cep' => '12235-240','tipo_cliente' => 'd'];
$clientes[]= ['name'=>'HSMV ','cnpj' => '54046081/0001-90','logradouro' => 'R. Romualdo Davoli','numero' => '25','bairro' => 'Jardim Vale do Sol','cidade' => 'São José dos Campos','complemento' => '','cep' => '12238-577','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'Restaurante Brasil','cnpj' => '','logradouro' => 'Espaço Eldorado','numero' => 'S/N','bairro' => 'Condominio Eldorado','cidade' => 'São José dos Campos','complemento' => '','cep' => '12238-565','tipo_cliente' => 'c'];
$clientes[]= ['name'=>'Wireflex (Restaurante Brasil)','cnpj' => '','logradouro' => 'R. Joaçaba','numero' => '10','bairro' => 'Chácaras Reunidas','cidade' => 'São José dos Campos','complemento' => '','cep' => '12238-530','tipo_cliente' => 'c'];
$clientes[]= ['name'=>'Marcos Dom Pedro','cnpj' => '','logradouro' => 'Av. 10','numero' => '127','bairro' => 'Dom Pedro','cidade' => 'São José dos Campos','complemento' => '','cep' => '12232-865','tipo_cliente' => 'a'];
$clientes[]= ['name'=>'PMSJC SSM Sul 2','cnpj' => '46643466/0001-06','logradouro' => 'Rua Angêlo Belmiro Pinto','numero' => '1263','bairro' => 'Conjunto Elmano Veloso','cidade' => 'São José dos Campos','complemento' => '','cep' => '12234-540','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'Lumavale','cnpj' => '07146092/0001-61','logradouro' => 'Av. Leonor de Almeida Ribeiro Souto','numero' => '59','bairro' => 'Res. Uniao','cidade' => 'São José dos Campos','complemento' => '','cep' => '12239-050','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'Utec','cnpj' => '','logradouro' => 'R. José de Campos','numero' => '96','bairro' => 'Cidade Morumbi','cidade' => 'São José dos Campos','complemento' => '','cep' => '12236-650','tipo_cliente' => 'd'];
$clientes[]= ['name'=>'Fátima','cnpj' => '','logradouro' => 'R. Adriano Espindola','numero' => '221','bairro' => 'Cidade Morumbi','cidade' => 'São José dos Campos','complemento' => '','cep' => '12236-720','tipo_cliente' => 'a'];
$clientes[]= ['name'=>'Pardal','cnpj' => '','logradouro' => 'Av. Fortaleza','numero' => '509','bairro' => 'Parque Industrial','cidade' => 'São José dos Campos','complemento' => '','cep' => '12235-560','tipo_cliente' => 'a'];
$clientes[]= ['name'=>'CIETEL ','cnpj' => '27240030/0001-21','logradouro' => 'R. Romualdo Davoli','numero' => '310','bairro' => 'Jardim Vale do Sol','cidade' => 'São José dos Campos','complemento' => '','cep' => '12238-577','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'Filó','cnpj' => '','logradouro' => 'R. Candeias','numero' => '1836','bairro' => 'Vale do Sol','cidade' => 'São José dos Campos','complemento' => '','cep' => '12238-010','tipo_cliente' => 'a'];
$clientes[]= ['name'=>'Tião','cnpj' => '','logradouro' => 'Av. Joao de Oliveira e Silva','numero' => '13','bairro' => 'Campo dos Alemaes','cidade' => 'São José dos Campos','complemento' => '','cep' => '12239-290','tipo_cliente' => 'a'];
$clientes[]= ['name'=>'Francisca Júlia ','cnpj' => '61956496/0002-47','logradouro' => 'Estr. Dr. Bezerra de Menezes','numero' => '700','bairro' => 'Jardim Torrao de Ouro','cidade' => 'São José dos Campos','complemento' => '','cep' => '12229-380','tipo_cliente' => 'c'];
$clientes[]= ['name'=>'Sesi SJC','cnpj' => '03779133/0010-97','logradouro' => 'Av. Cidade Jardim','numero' => '4389','bairro' => 'Bosque dos Eucaliptos','cidade' => 'São José dos Campos','complemento' => '','cep' => '12232-000','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'PMSJC CAPS SUL','cnpj' => '46643466/0001-06','logradouro' => 'Rua: Piraju','numero' => '45','bairro' => 'Bosque dos Eucaliptos','cidade' => 'São José dos Campos','complemento' => '','cep' => '12233-780','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'Viação Mimo Jacareí','cnpj' => '01247689/0005-39','logradouro' => 'Av. Ademar Pereira de Barros','numero' => '1697','bairro' => 'Jardim Santa Maria','cidade' => 'Jacareí','complemento' => '','cep' => '12328-300','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'PSV','cnpj' => '03531880/0001-10','logradouro' => 'Av. Ademar Pereira de Barros','numero' => '995','bairro' => 'Jardim Santa Maria','cidade' => 'Jacareí','complemento' => '','cep' => '12328-300','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'Winoa IKK ( Qualitá)','cnpj' => '44342914/0001-06','logradouro' => 'Av. Industrial','numero' => '500','bairro' => 'Jardim Emilia','cidade' => 'Jacareí','complemento' => '','cep' => '12321-500','tipo_cliente' => 'd'];
$clientes[]= ['name'=>'Adatex Matriz (Ideal)','cnpj' => '01227687/0001-65','logradouro' => 'R. Março Mehler','numero' => '45','bairro' => 'São João','cidade' => 'Jacareí','complemento' => '','cep' => '12322-440','tipo_cliente' => 'c'];
$clientes[]= ['name'=>'Adatex Filial (Ideal)','cnpj' => '01227687/0001-65','logradouro' => 'Rod. General Euryale de Jesus Zerbine','numero' => '6801','bairro' => 'Zona de Adensamento Controlado (ZAC São Silvestre)','cidade' => 'Jacareí','complemento' => '','cep' => '12340-010','tipo_cliente' => 'c'];
$clientes[]= ['name'=>'Santa Casa Jacareí','cnpj' => '50471564/0001-80','logradouro' => 'R. Antônio Afonso','numero' => '119','bairro' => 'Centro','cidade' => 'Jacareí','complemento' => '','cep' => '12327-270','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Hospital Antonio Afonso','cnpj' => '61879813/0001-98','logradouro' => 'R. Antônio Afonso','numero' => '307','bairro' => 'Centro','cidade' => 'Jacareí','complemento' => '','cep' => '12327-270','tipo_cliente' => 'd'];
$clientes[]= ['name'=>'Policlin Jacarei ','cnpj' => '45184066/0004-60','logradouro' => 'Rua Dr. Pompílio Mercadante','numero' => '398','bairro' => 'Centro','cidade' => 'Jacareí','complemento' => '','cep' => '12308-510','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'Hospital Alvorada','cnpj' => '50482298/0001-91','logradouro' => 'R. Minas Gerais','numero' => '180','bairro' => 'Vila Pinheiro','cidade' => 'Jacareí','complemento' => '','cep' => '12307-060','tipo_cliente' => 'd'];
$clientes[]= ['name'=>'Conde Atacado','cnpj' => '71605265/0102-05','logradouro' => 'SP 066','numero' => '5300','bairro' => 'Eldorado','cidade' => 'São José dos Campos','complemento' => '','cep' => '12238-580','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'Rosemary ','cnpj' => '','logradouro' => 'R. Caravelas','numero' => '356','bairro' => 'Vale do Sol','cidade' => 'São José dos Campos','complemento' => '','cep' => '12238-170','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'Polipet Delivery - Carlos','cnpj' => '05886844/0003-67','logradouro' => 'Rua das lobelias','numero' => '108','bairro' => 'Jardim das Indústrias','cidade' => 'São José dos Campos','complemento' => '','cep' => '12240-460','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'Polipet Delivery - Talitha','cnpj' => '05886844/0003-67','logradouro' => 'Rua das lobelias','numero' => '108','bairro' => 'Jardim das Indústrias','cidade' => 'São José dos Campos','complemento' => '','cep' => '12240-460','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'Polipet Delivery - Beraldi','cnpj' => '05886844/0003-67','logradouro' => 'Rua das lobelias','numero' => '108','bairro' => 'Jardim das Indústrias','cidade' => 'São José dos Campos','complemento' => '','cep' => '12240-460','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'Centro Médico Vivalle','cnpj' => '49930514/0001-35','logradouro' => 'R. Carlos Maria Auricchio','numero' => '70','bairro' => 'Jardim Aquárius','cidade' => 'São José dos Campos','complemento' => '','cep' => '12246-876','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Sodimac (Bella Nutri)','cnpj' => '32136274/0001-07','logradouro' => 'Av. Dep. Benedito Matarazzo','numero' => '5301','bairro' => 'Jardim Aquárius','cidade' => 'São José dos Campos','complemento' => '','cep' => '12215-691','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'Sams Clube (Sapore)','cnpj' => '67945071/0001-38','logradouro' => 'Av. Cassiano Ricardo','numero' => '1993','bairro' => 'Jardim Alvorada','cidade' => 'São José dos Campos','complemento' => '','cep' => '12240-540','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'HortShop Jd Indústrias','cnpj' => '09535503/0001-36','logradouro' => 'Av. Dr. João Baptista Soares de Queiroz Júnior','numero' => '2090','bairro' => 'Jardim das Industrias','cidade' => 'São José dos Campos','complemento' => '','cep' => '12240-000','tipo_cliente' => 'b'];
$clientes[]= ['name'=>'Mater Dei (Sapore)','cnpj' => '67945071/0001-38','logradouro' => 'Av. Lineu de Moura','numero' => '1055','bairro' => 'Urbanova','cidade' => 'São José dos Campos','complemento' => '','cep' => '12244-380','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Colegio Poliedro ','cnpj' => '08204478/0001-45','logradouro' => 'Av. Dr. Eduardo Cury','numero' => '50','bairro' => 'Jardim das Colinas','cidade' => 'São José dos Campos','complemento' => '','cep' => '12242-001','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Esfera (Sapore)','cnpj' => '67945071/0001-38','logradouro' => 'Av. Jorge Zarur','numero' => '650','bairro' => 'Jardim Aquarius','cidade' => 'São José dos Campos','complemento' => '','cep' => '12242-020','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Royal Care (Ótima)','cnpj' => '48717946/0001-08','logradouro' => 'R. Itajai','numero' => '50','bairro' => 'Altos do Esplanada','cidade' => 'São José dos Campos','complemento' => '','cep' => '12246-858','tipo_cliente' => 'c'];
$clientes[]= ['name'=>'Polipet Vidoca','cnpj' => '05886844/0003-67','logradouro' => 'Av. Jorge Zarur','numero' => '531','bairro' => 'Vila Ema','cidade' => 'São José dos Campos','complemento' => '','cep' => '12243-081','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'CEC','cnpj' => '00464450/0001-35','logradouro' => 'Av. Dr. João Baptista Soares de Queiroz Júnior','numero' => '30','bairro' => 'Jardim das Indústrias','cidade' => 'São José dos Campos','complemento' => '','cep' => '12240-000','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'Polipet Parque','cnpj' => '05886844/0005-29','logradouro' => 'Rua Itumbiara','numero' => '21','bairro' => 'Parque Industrial','cidade' => 'São José dos Campos','complemento' => '','cep' => '12235-740','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'Asilo Tivoli ','cnpj' => '36226466/0001-57','logradouro' => 'Av. Tivoli','numero' => '195','bairro' => 'Vila Betânia','cidade' => 'São José dos Campos','complemento' => '','cep' => '12245-481','tipo_cliente' => 'c'];
$clientes[]= ['name'=>'Hospital Antoninho (Rede Madre)','cnpj' => '60194990/0007-63','logradouro' => 'Av. Heitor Villa Lobos','numero' => '1961','bairro' => 'Jardim Renata','cidade' => 'São José dos Campos','complemento' => '','cep' => '12245-280','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'PMSJC Guarda Pq Santos D.','cnpj' => '46643466/0001-06','logradouro' => 'R. Eng. Prudente Meireles de Morais','numero' => '1000','bairro' => 'Vila Adyana','cidade' => 'São José dos Campos','complemento' => '','cep' => '12243-750','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC SSM Pq. Santos D.','cnpj' => '46643466/0001-06','logradouro' => 'R. Eng. Prudente Meireles de Morais','numero' => '1000','bairro' => 'Vila Adyana','cidade' => 'São José dos Campos','complemento' => '','cep' => '12243-750','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'Curso Poliedro','cnpj' => '96488515/0001-51','logradouro' => 'Tv. João Friggi','numero' => 'S/N','bairro' => 'Jardim Vale do Paraíso','cidade' => 'São José dos Campos','complemento' => '','cep' => '12245-570','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Abrigo AVD','cnpj' => '09123386/0001-01','logradouro' => 'R. Maj. Antônio Domingues','numero' => '227','bairro' => 'Centro','cidade' => 'São José dos Campos','complemento' => '','cep' => '12245-750','tipo_cliente' => 'd'];
$clientes[]= ['name'=>'Hotel Lisboa ','cnpj' => '14503618/0001-89','logradouro' => 'R. Maj. Antônio Domingues','numero' => '344','bairro' => 'Centro','cidade' => 'São José dos Campos','complemento' => '','cep' => '12245-750','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'Santa Casa SJC','cnpj' => '45186053/0001-87','logradouro' => 'Rua Antonio Saes','numero' => '376','bairro' => 'Centro','cidade' => 'São José dos Campos','complemento' => '','cep' => '12210-040','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'CRF Presidio Feminino','cnpj' => '96291141/0150-20','logradouro' => 'Tv. Francisco Almada','numero' => '81','bairro' => 'Centro','cidade' => 'São José dos Campos','complemento' => '','cep' => '12245-916','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Abrigo Feminino (Apar)','cnpj' => '01680455/0001-68','logradouro' => 'R. República do Líbano','numero' => '449','bairro' => 'Jardim Oswaldo Cruz','cidade' => 'São José dos Campos','complemento' => '','cep' => '12216-590','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'Abrigo Masculino (Apar)','cnpj' => '01680455/0001-68','logradouro' => 'R. Maj. Antônio Domingues','numero' => '227','bairro' => 'Centro','cidade' => 'São José dos Campos','complemento' => '','cep' => '12245-750','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'Asilo Vilas Lobos','cnpj' => '36226466/0001-57','logradouro' => 'R. Carvalho de Araújo','numero' => '168','bairro' => 'Vila Maria','cidade' => 'São José dos Campos','complemento' => '','cep' => '12209-390','tipo_cliente' => 'c'];
$clientes[]= ['name'=>'PMSJC SSM Pq Cidade','cnpj' => '46643466/0001-06','logradouro' => 'Av. Olivo Gomes','numero' => '100','bairro' => 'Santana','cidade' => 'São José dos Campos','complemento' => '','cep' => '12211-115','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC Manutenção Saúde Pq  da Cidade','cnpj' => '46643466/0001-06','logradouro' => 'Av. Olivo Gomes','numero' => '100','bairro' => 'Santana','cidade' => 'São José dos Campos','complemento' => '','cep' => '12211-115','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC Esportes Pq Cidade','cnpj' => '46643466/0001-06','logradouro' => 'Av. Olivo Gomes','numero' => '100','bairro' => 'Santana','cidade' => 'São José dos Campos','complemento' => '','cep' => '12211-115','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC Urbanismo Pq Cidade','cnpj' => '46643466/0001-06','logradouro' => 'Av. Olivo Gomes','numero' => '100','bairro' => 'Santana','cidade' => 'São José dos Campos','complemento' => '','cep' => '12211-115','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC Educação CEFE','cnpj' => '46643466/0001-06','logradouro' => 'Av. Olivo Gomes','numero' => '250','bairro' => 'Santana','cidade' => 'São José dos Campos','complemento' => '','cep' => '12211-115','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC Guarda CEFE EQP','cnpj' => '46643466/0001-06','logradouro' => 'Av. Olivo Gomes','numero' => '250','bairro' => 'Santana','cidade' => 'São José dos Campos','complemento' => '','cep' => '12211-115','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC Cidade da Educação 2','cnpj' => '46643466/0001-06','logradouro' => 'Estr. Mun. Glaudistom Pereira de Oliveira','numero' => '811','bairro' => 'Jardim Flamboyant','cidade' => 'São José dos Campos','complemento' => '','cep' => '12228-010','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC SSM Centro','cnpj' => '46643466/0001-06','logradouro' => 'Avenida Jorge Zarur','numero' => '2201','bairro' => 'Vila Letonia','cidade' => 'São José dos Campos','complemento' => '','cep' => '12243-081','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC SSM Sul 1','cnpj' => '46643466/0001-06','logradouro' => 'Avenida João Batista Souza Soares','numero' => '180','bairro' => 'Parque Industrial','cidade' => 'São José dos Campos','complemento' => '','cep' => '12236-662','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC SSM Fac','cnpj' => '46643466/0001-06','logradouro' => 'Avenida João Batista Souza Soares','numero' => '180','bairro' => 'Parque Industrial','cidade' => 'São José dos Campos','complemento' => '','cep' => '12236-662','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC SSM Portelinha','cnpj' => '46643466/0001-06','logradouro' => 'Avenida João Batista Souza Soares','numero' => '180','bairro' => 'Parque Industrial','cidade' => 'São José dos Campos','complemento' => '','cep' => '12236-662','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC SSM Carpintaria','cnpj' => '46643466/0001-06','logradouro' => 'Avenida João Batista Souza Soares','numero' => '180','bairro' => 'Parque Industrial','cidade' => 'São José dos Campos','complemento' => '','cep' => '12236-662','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC SSM Serralheria','cnpj' => '46643466/0001-06','logradouro' => 'Avenida João Batista Souza Soares','numero' => '180','bairro' => 'Parque Industrial','cidade' => 'São José dos Campos','complemento' => '','cep' => '12236-662','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'Techal','cnpj' => '02662541/0001-00','logradouro' => 'Av. Sebastião Henrique da Cunha Pontes','numero' => '8500','bairro' => 'Chácaras Reunidas','cidade' => 'São José dos Campos','complemento' => '','cep' => '12237-970','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'Orguel','cnpj' => '19537752/0020-87','logradouro' => 'R. Guacuí','numero' => '328','bairro' => 'Chácaras Reunidas','cidade' => 'São José dos Campos','complemento' => '','cep' => '12238-480','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'Poliedro CD ','cnpj' => '05783379/0006-81','logradouro' => 'Av. Central ','numero' => '150','bairro' => 'Chácaras Reunidas','cidade' => 'São José dos Campos','complemento' => '','cep' => '12238-430','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Poliedro CD II Novo','cnpj' => '18171089/0001-14','logradouro' => 'Av Dr. Sebastião Henrique da Cunha','numero' => '1658','bairro' => 'Chacaras Reunidas','cidade' => 'São José dos Campos','complemento' => '','cep' => '12237-823','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Poliedro CEV','cnpj' => '05783379/0001-77','logradouro' => 'Av. George Eastman','numero' => '1011','bairro' => 'Conj. Res. Trinta e Um de Marco','cidade' => 'São José dos Campos','complemento' => '','cep' => '12237-640','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Ferreira','cnpj' => '16422783/0001-31','logradouro' => 'Av. George Eastman','numero' => '1011','bairro' => 'Conj. Res. Trinta e Um de Marco','cidade' => 'São José dos Campos','complemento' => 'Prédio 16','cep' => '12237-640','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Kodak','cnpj' => '69032720/0001-35','logradouro' => 'Av. George Eastman','numero' => '2901','bairro' => 'Conj. Res. Trinta e Um de Marco','cidade' => 'São José dos Campos','complemento' => '','cep' => '12237-640','tipo_cliente' => 'd'];
$clientes[]= ['name'=>'Calfer','cnpj' => '01305262/0001-27','logradouro' => 'R. José Vicente de Paula','numero' => '213','bairro' => 'Pq. Santos Dumont','cidade' => 'São José dos Campos','complemento' => '','cep' => '12227-810','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'Digex (Qualita)','cnpj' => '44342914/0001-06','logradouro' => 'Av. Brg. Faria Lima','numero' => 'S/N','bairro' => 'Campus do CTA','cidade' => 'São José dos Campos','complemento' => 'Aeroporto','cep' => '12227-000','tipo_cliente' => 'd'];
$clientes[]= ['name'=>'PMSJC Cidade de Educação','cnpj' => '46643466/0001-06','logradouro' => 'Estr. Mun. Glaudistom Pereira de Oliveira','numero' => '811','bairro' => 'Jardim Flamboyant','cidade' => 'São José dos Campos','complemento' => '','cep' => '12228-010','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'Abordagem (Rodoviária)','cnpj' => '09123386/0001-01','logradouro' => 'Rua Itororo','numero' => '353','bairro' => 'Vila Piratininga','cidade' => 'São José dos Campos','complemento' => '','cep' => '12216-440','tipo_cliente' => 'd'];
$clientes[]= ['name'=>'Cartão Para Todos','cnpj' => '12061049/0001-33','logradouro' => 'Rua Vilaça','numero' => '461','bairro' => 'Centro.','cidade' => 'São José dos Campos','complemento' => '','cep' => '12210-000','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'PMSJC Tiro de Guerra','cnpj' => '46643466/0001-06','logradouro' => 'R. Saigiro Nakamura','numero' => '500','bairro' => 'Vila Industrial','cidade' => 'São José dos Campos','complemento' => '','cep' => '12220-280','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'Casa Brasil ','cnpj' => '61956496/0012-19','logradouro' => 'Avenida Brasil','numero' => 'S/N','bairro' => 'Monte Castelo','cidade' => 'São José dos Campos','complemento' => '','cep' => '12215-000','tipo_cliente' => 'd'];
$clientes[]= ['name'=>'Sr. Mignon','cnpj' => '36624431/0001-76','logradouro' => 'Av. dos Astronautas','numero' => '975','bairro' => 'Jardim Sout','cidade' => 'São José dos Campos','complemento' => '','cep' => '12227-010','tipo_cliente' => 'c'];
$clientes[]= ['name'=>'Ótima','cnpj' => '48717946/0001-08','logradouro' => 'Rua Rosa Coulicoff Diamante','numero' => '101','bairro' => 'Jardim Diamante','cidade' => 'São José dos Campos','complemento' => '','cep' => '12223-210','tipo_cliente' => 'c'];
$clientes[]= ['name'=>'Luzinete CAVAP','cnpj' => '','logradouro' => 'Acesso petrobras','numero' => '11','bairro' => 'Jardim Diamante','cidade' => 'São José dos Campos','complemento' => '','cep' => '12223-900','tipo_cliente' => 'c'];
$clientes[]= ['name'=>'UPA Novo Horizonte (Ótima)','cnpj' => '48717946/0001-08','logradouro' => 'Av. Pres. Tancredo Neves','numero' => '5120','bairro' => 'Parque Novo Horizont','cidade' => 'São José dos Campos','complemento' => '','cep' => '12225-011','tipo_cliente' => 'c'];
$clientes[]= ['name'=>'PMSJC SSM Leste 2','cnpj' => '46643466/0001-06','logradouro' => 'Estrada do Mato Dentro','numero' => '1300','bairro' => 'Dom Bosco','cidade' => 'São José dos Campos','complemento' => '','cep' => '12225-470','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'Premovale (Dom Rubi)','cnpj' => '16580640/0001-58','logradouro' => 'Estr. Mun. Nossa Sra. Aparecida','numero' => '1991','bairro' => 'Paiol','cidade' => 'Caçapava','complemento' => '','cep' => '12295-429','tipo_cliente' => 'b'];
$clientes[]= ['name'=>'Rosemberg (Ideal)','cnpj' => '01227687/0001-65','logradouro' => 'Av. Cabletech','numero' => '601','bairro' => 'Guamirim','cidade' => 'Caçapava','complemento' => '','cep' => '12295-230','tipo_cliente' => 'c'];
$clientes[]= ['name'=>'Treves Caçapava (Sapore)','cnpj' => '67945071/0001-38','logradouro' => 'Av. Henry Nestlé','numero' => '2222','bairro' => 'Vila Galvão','cidade' => 'Caçapava','complemento' => '','cep' => '12286-170','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'CPW (Sapore)','cnpj' => '67945071/0001-38','logradouro' => 'R. Cap. Airton Araújo','numero' => '200','bairro' => 'Vila Galvão','cidade' => 'Caçapava','complemento' => '','cep' => '12286-180','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Merenda Caçapava','cnpj' => '45189305/0001-21','logradouro' => 'R. Valentim Paz Vidal','numero' => '197','bairro' => 'Res. Nancy','cidade' => 'Caçapava','complemento' => '','cep' => '12286-530','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'FUSAM (Nutrindo)','cnpj' => '50453703/0001-43','logradouro' => 'Av. Dr. Pereira de Mattos','numero' => '63','bairro' => 'Centro','cidade' => 'Caçapava','complemento' => '','cep' => '12281-450','tipo_cliente' => 'c'];
$clientes[]= ['name'=>'Yushiro (Ótima)','cnpj' => '48717946/0001-08','logradouro' => 'Av. Henry Nestlé','numero' => '3100','bairro' => 'Vila Galvão','cidade' => 'Caçapava','complemento' => '','cep' => '12286-170','tipo_cliente' => 'c'];
$clientes[]= ['name'=>'UPA Eugênio de Melo (Ótima)','cnpj' => '48717946/0001-08','logradouro' => 'R. Gen. Eugênio de Augusto Melo','numero' => '101','bairro' => 'Eugênio de Melo','cidade' => 'São José dos Campos','complemento' => '','cep' => '12247-190','tipo_cliente' => 'c'];
$clientes[]= ['name'=>'PMSJC GUARDA Eugênio de Melo','cnpj' => '46643466/0001-06','logradouro' => 'R. Quinze de Novembro','numero' => '259','bairro' => 'Eugênio de Melo','cidade' => 'São José dos Campos','complemento' => '','cep' => '12247-210','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC SSM Eugênio de Melo','cnpj' => '46643466/0001-06','logradouro' => 'R. Quinze de Novembro','numero' => '259','bairro' => 'Eugênio de Melo','cidade' => 'São José dos Campos','complemento' => '','cep' => '12247-210','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'Viação Mimo Eug. Melo','cnpj' => '01274689/0005-39','logradouro' => 'Rua Ambrosio Molina','numero' => '1151','bairro' => 'Eugênio de Melo','cidade' => 'São José dos Campos','complemento' => '','cep' => '12247-000','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'ELTEK - DELTA','cnpj' => '75584110/0082-02','logradouro' => 'Estr. Velha Rio São Paulo','numero' => '5300','bairro' => 'Eugênio de Melo','cidade' => 'São José dos Campos','complemento' => '','cep' => '12237-652','tipo_cliente' => 'd'];
$clientes[]= ['name'=>'Denigris (Ideal)','cnpj' => '01227687/0001-65','logradouro' => 'Av. Dep. Benedito Matarazzo','numero' => '13131','bairro' => 'Vila Tatetuba','cidade' => 'São José dos Campos','complemento' => '','cep' => '12220-610','tipo_cliente' => 'c'];
$clientes[]= ['name'=>'Serralharia Farmaconde','cnpj' => '10264525/0001-98','logradouro' => 'Francisco Goncalves Fonseca','numero' => '125','bairro' => 'Eldorado','cidade' => 'São José dos Campos','complemento' => '','cep' => '12238-575','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'Grafica Farmaconde','cnpj' => '27945133/0001-97','logradouro' => 'Francisco Goncalves Fonseca','numero' => '125','bairro' => 'Eldorado','cidade' => 'São José dos Campos','complemento' => '','cep' => '12238-575','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'BCA (Sr Mignon)','cnpj' => '36624431/0001-76','logradouro' => 'Av. Eng. Juarez de Siqueira Brito Vanderlei','numero' => '180','bairro' => 'Eldorado','cidade' => 'São José dos Campos','complemento' => '','cep' => '12238-565','tipo_cliente' => 'c'];
$clientes[]= ['name'=>'Ultimate Eldorado','cnpj' => '06876242/0001-20','logradouro' => 'Av. Eng. Juarez de Siqueira Brito Vanderlei','numero' => '360','bairro' => 'Eldorado','cidade' => 'São José dos Campos','complemento' => '','cep' => '12238-565','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'LBV','cnpj' => '33915604/0527-70','logradouro' => 'Av. Manuel Vieira','numero' => '4219','bairro' => 'Morumbi','cidade' => 'São José dos Campos','complemento' => '','cep' => '12239-053','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'Paineiras','cnpj' => '','logradouro' => 'Av. Benedito Domingues de Oliveira','numero' => '106','bairro' => 'Morumbi','cidade' => 'São José dos Campos','complemento' => '','cep' => '12236-702','tipo_cliente' => 'a'];
$clientes[]= ['name'=>'Sueli','cnpj' => '','logradouro' => 'R. Joana Soares Ferreira','numero' => '1369','bairro' => 'Morumbi','cidade' => 'São José dos Campos','complemento' => '','cep' => '12236-420','tipo_cliente' => 'a'];
$clientes[]= ['name'=>'Camara Municipal','cnpj' => '50448935/0001-03','logradouro' => 'R. Des. Francisco Murilo Pinto','numero' => '33','bairro' => 'Vila Santa Luzia','cidade' => 'São José dos Campos','complemento' => '','cep' => '12209-535','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Polipet Vila Industrial','cnpj' => '05886844/0009-52','logradouro' => 'Av. João Marson','numero' => '2750','bairro' => 'Vila Industrial','cidade' => 'São José dos Campos','complemento' => '','cep' => '12220-360','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'Tegma (Sapore)','cnpj' => '60691250/0001-47','logradouro' => 'Estr. Mun. Martins Guimarães','numero' => '906','bairro' => 'Vila Ester','cidade' => 'São José dos Campos','complemento' => '','cep' => '12221-520','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Abrigo Família','cnpj' => '09123386/0001-01','logradouro' => 'Rua José Luiz Cembranelli','numero' => '40','bairro' => 'Vila Tesouro','cidade' => 'São José dos Campos','complemento' => '','cep' => '12221-740','tipo_cliente' => 'd'];
$clientes[]= ['name'=>'PMSJC Defesa Civil','cnpj' => '46643466/0001-06','logradouro' => 'R. Saigiro Nakamura','numero' => '10','bairro' => 'Vila Industrial','cidade' => 'São José dos Campos','complemento' => '','cep' => '12220-280','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC SSM Leste 1','cnpj' => '46643466/0001-06','logradouro' => 'Rua Saigiro Nakamura','numero' => '10','bairro' => 'Vila Industrial','cidade' => 'São José dos Campos','complemento' => '','cep' => '12220-280','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC SSM DMVE','cnpj' => '46643466/0001-06','logradouro' => 'Rua Saigiro Nakamura','numero' => '10','bairro' => 'Vila Industrial','cidade' => 'São José dos Campos','complemento' => '','cep' => '12220-280','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC SSM Elétrica','cnpj' => '46643466/0001-06','logradouro' => 'Rua Saigiro Nakamura','numero' => '10','bairro' => 'Vila Industrial','cidade' => 'São José dos Campos','complemento' => '','cep' => '12220-280','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC SSM Saneamento','cnpj' => '46643466/0001-06','logradouro' => 'Rua Saigiro Nakamura','numero' => '10','bairro' => 'Vila Industrial','cidade' => 'São José dos Campos','complemento' => '','cep' => '12220-280','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC SSM Hidráulica','cnpj' => '46643466/0001-06','logradouro' => 'Rua Saigiro Nakamura','numero' => '10','bairro' => 'Vila Industrial','cidade' => 'São José dos Campos','complemento' => '','cep' => '12220-280','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC SSM Antipichação','cnpj' => '46643466/0001-06','logradouro' => 'Rua Professor Felicio Sabastano','numero' => '401','bairro' => 'Vila Industrial','cidade' => 'São José dos Campos','complemento' => '','cep' => '12220-270','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC Fiscalização','cnpj' => '46643466/0001-06','logradouro' => 'Rua Saigiro Nakamura','numero' => '10','bairro' => 'Vila Industrial','cidade' => 'São José dos Campos','complemento' => '','cep' => '12220-280','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC Merenda Escolar ','cnpj' => '46643466/0001-06','logradouro' => 'Rua Professor Felicio Sabastano','numero' => '401','bairro' => 'Vila Industrial','cidade' => 'São José dos Campos','complemento' => '','cep' => '12220-270','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC GUARDA Ensino','cnpj' => '46643466/0001-06','logradouro' => 'Rua Professor Felicio Sabastano','numero' => '401','bairro' => 'Vila Industrial','cidade' => 'São José dos Campos','complemento' => '','cep' => '12220-270','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC GUARDA Sede Operacional','cnpj' => '46643466/0001-06','logradouro' => 'Rua Felício Savastano','numero' => '401','bairro' => 'Vila Industrial','cidade' => 'São José dos Campos','complemento' => '','cep' => '12220-270','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC GUARDA ADM','cnpj' => '46643466/0001-06','logradouro' => 'Rua Professor Felicio Sabastano','numero' => '401','bairro' => 'Vila Industrial','cidade' => 'São José dos Campos','complemento' => '','cep' => '12220-270','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC GUARDA Anjos','cnpj' => '46643466/0001-06','logradouro' => 'Rua Felício Savastano','numero' => '401','bairro' => 'Vila industrial','cidade' => 'São José dos Campos','complemento' => '','cep' => '12220-270','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC GUARDA GAPE','cnpj' => '46643466/0001-06','logradouro' => 'Rua Professor Felicio Sabastano','numero' => '401','bairro' => 'Vila Industrial','cidade' => 'São José dos Campos','complemento' => '','cep' => '12220-270','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC GUARDA GTAM','cnpj' => '46643466/0001-06','logradouro' => 'Rua Professor Felicio Sabastano','numero' => '401','bairro' => 'Vila Industrial','cidade' => 'São José dos Campos','complemento' => '','cep' => '12220-270','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC GUARDA SEPAC','cnpj' => '46643466/0001-06','logradouro' => 'Rua Professor Felicio Sabastano','numero' => '401','bairro' => 'Vila Industrial','cidade' => 'São José dos Campos','complemento' => '','cep' => '12220-270','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC Almoxarifado Central','cnpj' => '46643466/0001-06','logradouro' => 'R. Prof. Felício Savastano','numero' => '401','bairro' => 'Vila Industrial','cidade' => 'São José dos Campos','complemento' => '','cep' => '12220-270','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC Manutenção da Saúde','cnpj' => '46643466/0001-06','logradouro' => 'Rua Professor Felicio Sabastano','numero' => '401','bairro' => 'Vila Industrial','cidade' => 'São José dos Campos','complemento' => '','cep' => '12220-270','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC Almoxarifado Saúde','cnpj' => '46643466/0001-06','logradouro' => 'R. Prof. Felício Savastano','numero' => '401','bairro' => 'Vila Industrial','cidade' => 'São José dos Campos','complemento' => '','cep' => '12220-270','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC Educação Vila Industrial','cnpj' => '46643466/0001-06','logradouro' => 'R. Prof. Felício Savastano','numero' => '297','bairro' => 'Vila Industrial','cidade' => 'São José dos Campos','complemento' => '','cep' => '12220-270','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC Cidade da Educação 1','cnpj' => '46643466/0001-06','logradouro' => 'Estrada Municipal Glaudistom Pereira de Oliveira','numero' => '811','bairro' => 'Putim','cidade' => 'São José dos Campos','complemento' => '','cep' => '12228-010','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'Urbam Vila','cnpj' => '03345887/0001-48','logradouro' => 'Rua Dr. Ricardo Edwards','numero' => '100','bairro' => 'Vila Industrial','cidade' => 'São José dos Campos','complemento' => '','cep' => '12220-290','tipo_cliente' => 'c'];
$clientes[]= ['name'=>'Joseense Ônibus','cnpj' => '','logradouro' => 'Rua Aldo Jose de Souza','numero' => '470','bairro' => 'Vila Industrial','cidade' => 'São José dos Campos','complemento' => '','cep' => '12230-002','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'PMSJC SSM Sede','cnpj' => '46643466/0001-06','logradouro' => 'Av. Dr. Nelson D Avilla','numero' => '658','bairro' => 'Centro','cidade' => 'São José dos Campos','complemento' => '','cep' => '12245-031','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC SSM Concessionária','cnpj' => '46643466/0001-06','logradouro' => 'Av. Dr. Nelson D Avilla','numero' => '658','bairro' => 'Centro','cidade' => 'São José dos Campos','complemento' => '','cep' => '12245-031','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC SSM Suprimentos','cnpj' => '46643466/0001-06','logradouro' => 'Av. Dr. Nelson D Avilla','numero' => '658','bairro' => 'Centro','cidade' => 'São José dos Campos','complemento' => '','cep' => '12245-031','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC SSM Informática','cnpj' => '46643466/0001-06','logradouro' => 'Av. Dr. Nelson D Avilla','numero' => '658','bairro' => 'Centro','cidade' => 'São José dos Campos','complemento' => '','cep' => '12245-031','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC SSM Gabinete','cnpj' => '46643466/0001-06','logradouro' => 'Av. Dr. Nelson D Avilla','numero' => '658','bairro' => 'Centro','cidade' => 'São José dos Campos','complemento' => '','cep' => '12245-031','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'PMSJC SSM Poço Teotonio','cnpj' => '46643466/0001-06','logradouro' => 'Av. Dr. Nelson D Avilla','numero' => '658','bairro' => 'Centro','cidade' => 'São José dos Campos','complemento' => '','cep' => '12245-031','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'Sanatório Maria Imaculada (Rede Madre)','cnpj' => '60194990/0002-59','logradouro' => 'Major Antonio Domingues','numero' => '244','bairro' => 'Centro','cidade' => 'São José dos Campos','complemento' => '','cep' => '12245-750','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Clinica Amor e Saude ','cnpj' => '39840362/0001-26','logradouro' => 'R. Francisco Paes','numero' => '105','bairro' => 'Centro','cidade' => 'São José dos Campos','complemento' => '','cep' => '12210-100','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'Usimaza','cnpj' => '09111405/0001-71','logradouro' => 'Travessa Quirino Custódio da Silva','numero' => '51','bairro' => 'Santana','cidade' => 'São José dos Campos','complemento' => '','cep' => '12211-181','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'SENAI','cnpj' => '','logradouro' => 'Rua Pedro Rachid','numero' => '304','bairro' => 'Santana','cidade' => 'São José dos Campos','complemento' => '','cep' => '12212-100','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'PMSJC Paço Municipal','cnpj' => '46643466/0001-06','logradouro' => 'Rua jose de Alencar','numero' => '123','bairro' => 'Centro','cidade' => 'São José dos Campos','complemento' => '','cep' => '12209-530','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'Casa de Repouso','cnpj' => '31402148/0001-86','logradouro' => 'R. Sebastiao Humel','numero' => '795','bairro' => 'Centro','cidade' => 'São José dos Campos','complemento' => '','cep' => '12210-200','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'PMSJC CAPS Centro Norte','cnpj' => '46643466/0001-06','logradouro' => 'R. Sebastião Humel','numero' => '785','bairro' => 'Centro','cidade' => 'São José dos Campos','complemento' => '','cep' => '12210-200','tipo_cliente' => 'f'];
$clientes[]= ['name'=>'Imagem (Ideal)','cnpj' => '01227687/0001-65','logradouro' => 'R. Joaçaba','numero' => '31','bairro' => 'Chácaras Reunidas','cidade' => 'São José dos Campos','complemento' => '','cep' => '12238-500','tipo_cliente' => 'c'];
$clientes[]= ['name'=>'Padaria Nova Esperanca','cnpj' => '','logradouro' => 'R. Odete Garcia','numero' => '1399','bairro' => 'Morumbi','cidade' => 'São José dos Campos','complemento' => '','cep' => '12236-430','tipo_cliente' => 'a'];
$clientes[]= ['name'=>'Santa Paula','cnpj' => '','logradouro' => 'R. Jose Conceicao Barreiro','numero' => '264','bairro' => 'Santa Paula','cidade' => 'São José dos Campos','complemento' => '','cep' => '12302-224','tipo_cliente' => 'c'];
$clientes[]= ['name'=>'Retifica RM','cnpj' => '','logradouro' => 'R. Bacabal','numero' => '2210','bairro' => 'Parque Industrial','cidade' => 'São José dos Campos','complemento' => '','cep' => '12235-681','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'Graúna','cnpj' => '03011370/0001-12','logradouro' => 'R. Januaria','numero' => '1100','bairro' => 'Chacaras reunidas','cidade' => 'São José dos Campos','complemento' => '','cep' => '12238-500','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'Contain','cnpj' => '31259349/0001-76','logradouro' => 'Av. Orlando Felipe Bonano','numero' => '705','bairro' => 'Jardim Santa Maria','cidade' => 'São José dos Campos','complemento' => '','cep' => '12328-210','tipo_cliente' => 'a'];
$clientes[]= ['name'=>'Jairo','cnpj' => '','logradouro' => 'R. Corifeu de Azevedo Marques','numero' => '357','bairro' => 'Limoeiro','cidade' => 'São José dos Campos','complemento' => '','cep' => '12240-780','tipo_cliente' => 'a'];
$clientes[]= ['name'=>'Johnson (Sodexo)','cnpj' => '49930514/0001-35','logradouro' => 'Rodovia Presidente Dutra','numero' => '','bairro' => 'Jardim das Industrias','cidade' => 'São José dos Campos','complemento' => '','cep' => '04028-000','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Bombeiros Jacareí (Boas Vindas)','cnpj' => '66140955/0001-52','logradouro' => 'Av Siqueira Campos','numero' => 'S/N','bairro' => 'Vila Martinez','cidade' => 'Jacareí','complemento' => '','cep' => '12307-190','tipo_cliente' => 'd'];
$clientes[]= ['name'=>'JG Indústria do Sabor','cnpj' => '04.099.703/0001-70','logradouro' => 'DOUTOR SEBASTIAO HENRIQUE DA CUNHA PONTES','numero' => '8300','bairro' => 'Century','cidade' => 'São José dos Campos','complemento' => '','cep' => '12230-300','tipo_cliente' => 'h'];
$clientes[]= ['name'=>'Emax','cnpj' => '09.064.068/0001-09','logradouro' => 'R. Arnaldo Domingos Mota','numero' => '105','bairro' => 'Eldorado','cidade' => 'São José dos Campos','complemento' => '','cep' => '12238-573','tipo_cliente' => 'e'];
$clientes[]= ['name'=>'Porto Vale','cnpj' => '07.081.058/0001-56','logradouro' => 'Avenida Comendador de Vicente Paulo Penido,','numero' => '374','bairro' => 'Jardim Aquarius','cidade' => 'São José dos Campos','complemento' => '','cep' => '12246-856','tipo_cliente' => 'e'];
        
        foreach ($clientes as $cliente) {
            Cliente::create($cliente);
        }
    }
}
