version: "3"
services:
  db:
    image: postgis/postgis:latest
    container_name: db
    networks:
      - rede-aplicacao
    environment:
      POSTGRES_DB: panificadora_nova_esperanca
      POSTGRES_USER: panificadora_nova_esperanca
      POSTGRES_PASSWORD: panificadora_nova_esperanca_develop
    ports:
      - "54321:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d panificadora_nova_esperanca -U panificadora_nova_esperanca"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      dockerfile: './Dockerfile'
      context: .
    container_name: padaria_homolog
    ports:
      - "9000:9000"
    networks:
      - rede-aplicacao
    env_file:
      - .env.example  # <- NÃO monte diretamente o .env do host
    volumes:
      - ./app:/var/www/html/app
      - ./bootstrap:/var/www/html/bootstrap
      - ./config:/var/www/html/config
      - ./database:/var/www/html/database
      - ./lang:/var/www/html/lang
      - ./resources:/var/www/html/resources
      - ./routes:/var/www/html/routes
      - ./storage:/var/www/html/storage
      - ./stubs:/var/www/html/stubs
      - ./tests:/var/www/html/tests
      - ./public:/var/www/html/public
      - ./start.sh:/start.sh
    depends_on:
      db:
        condition: service_healthy
    command: ["/bin/bash", "/start.sh"]

  nginx:
    build:
      dockerfile: './nginx-dev.dockerfile'
      context: .
    container_name: nginx-server
    volumes:
      - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public  # Apenas a pasta pública precisa estar montada
    ports:
      - "80:80"
    networks:
      - rede-aplicacao
    depends_on:
      - app

networks:
  rede-aplicacao:
    driver: bridge

volumes:
  db_data:

